const names = require('./4-names')
const sayHi = require('./5-utils')
//console.log(names)
const data = require('./alternative-flavour')
require('./mind-grenade')
// console.log(data)
// sayHi ('susan')
// sayHi(names.peter)
// sayHi(names.john)
